language: node_js

node_js:
  - stable
  - 10
  - 8

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  include:
    - stage: deploy to github
      if: branch = master
      node_js: stable
      script:
        - yarn build
      deploy:
        provider: pages
        local-dir: demo/dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
