language: node_js

node_js:
  - stable
  - 10
  - 8

addons:
  sonarcloud:
    organization: inforsuite-github
    token:
      secure: $SONAR_CLOUD_TOKEN

script:
  - npm test

jobs:
  include:
    - stage: publish quality report
      node_js: stable
      script:
        - sonar-scanner
